/**
 * Mandi ERP Excel Export Engine
 * Generates formatted .xlsx workbooks locally using open-source xlsx
 * Follows Point 24: Header banner, bilingual columns, Subtotal, Grand Total, auto-filename
 */

import * as XLSX from 'xlsx';
import { Business } from '../types';

export interface ExcelColumn {
  headerEn: string;
  headerUrdu?: string;
  key: string;
  format?: 'currency' | 'weight' | 'number' | 'text';
}

export interface ExportExcelOptions {
  business: Business;
  reportName: string;
  dateRangeStr?: string;
  columns: ExcelColumn[];
  data: Record<string, any>[];
  subtotalRow?: Record<string, any>;
  grandTotalRow?: Record<string, any>;
  generatedBy?: string;
}

export function exportReportToExcel({
  business,
  reportName,
  dateRangeStr = new Date().toLocaleDateString('en-GB'),
  columns,
  data,
  subtotalRow,
  grandTotalRow,
  generatedBy = 'Admin'
}: ExportExcelOptions) {
  const wb = XLSX.utils.book_new();

  // Create formatted grid
  const sheetRows: any[][] = [];

  // Row 1: Business Header
  sheetRows.push([
    `${business.name} | ${business.nameUrdu} - ${business.address} - Phone: ${business.phone} - NTN: ${business.ntn}`
  ]);

  // Row 2: Report Meta
  sheetRows.push([
    `Report: ${reportName} | Date Range: ${dateRangeStr} | Currency: PKR (Rs.)`
  ]);

  // Empty separator
  sheetRows.push([]);

  // Row 4: Column Headers (Bilingual)
  const headerRow = columns.map(c => c.headerUrdu ? `${c.headerEn} / ${c.headerUrdu}` : c.headerEn);
  sheetRows.push(headerRow);

  // Data Rows
  data.forEach(item => {
    const row = columns.map(col => {
      const val = item[col.key];
      if (val === undefined || val === null) return '';
      if (col.format === 'currency') {
        return Number(val) || 0;
      }
      if (col.format === 'number' || col.format === 'weight') {
        return Number(val) || 0;
      }
      return String(val);
    });
    sheetRows.push(row);
  });

  // Subtotal Row if provided
  if (subtotalRow) {
    sheetRows.push([]);
    const subRow = columns.map((col, idx) => {
      if (idx === 0) return 'SUBTOTAL / ذیلی میزان:';
      const val = subtotalRow[col.key];
      return val !== undefined ? val : '';
    });
    sheetRows.push(subRow);
  }

  // Grand Total Row if provided
  if (grandTotalRow) {
    const grandRow = columns.map((col, idx) => {
      if (idx === 0) return 'GRAND TOTAL / کل میزان (PKR):';
      const val = grandTotalRow[col.key];
      return val !== undefined ? val : '';
    });
    sheetRows.push(grandRow);
  }

  // Footer Row
  sheetRows.push([]);
  const now = new Date().toLocaleString('en-PK');
  sheetRows.push([`Generated By: ${generatedBy} | Timestamp: ${now} | Grain Market Software ERP`]);

  // Create worksheet
  const ws = XLSX.utils.aoa_to_sheet(sheetRows);

  // Column widths
  ws['!cols'] = columns.map(col => ({
    wch: Math.max(col.headerEn.length + 8, 16)
  }));

  // Append sheet
  const cleanSheetName = reportName.replace(/[\\/*?[\]:]/g, ' ').substring(0, 31);
  XLSX.utils.book_append_sheet(wb, ws, cleanSheetName);

  // Sanitize business name for filename
  const cleanBizName = business.name.replace(/[^a-zA-Z0-9]/g, '_');
  const cleanRepName = reportName.replace(/[^a-zA-Z0-9]/g, '_');
  const dateTag = new Date().toISOString().slice(0, 10);
  const fileName = `${cleanRepName}_${dateTag}_${cleanBizName}.xlsx`;

  // Trigger browser download
  XLSX.writeFile(wb, fileName);
}
